######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 6 21:10:31 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Element.h Example.h
SOURCES += main.cpp
